FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN go build -o myapp ./cmd/api/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/myapp .
EXPOSE 8000
ENTRYPOINT ["./myapp"]